"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Button } from "@/components/ui/Button";
import { Dialog } from "@/components/ui/Dialog";
import { FieldError } from "@/components/ui/Primitives";
import { useToast } from "@/components/ui/Toast";
import { apiFetch } from "@/lib/api-client";
import type { Activity, ActivityInput, ActivityResponse, ActivityType, SeasonSummary } from "@/lib/api-types";
import { queryKeys } from "@/lib/query-keys";

const types = ["planting", "spraying", "irrigation", "fertilizer", "harvest", "note"] as const satisfies readonly ActivityType[];
const schema = z.object({ seasonId: z.string().min(1, "Choose a season."), type: z.enum(types), activityDate: z.string().min(1, "Choose a date."), quantity: z.number().nonnegative().nullable(), quantityUnit: z.string().trim().max(30).nullable(), costAmount: z.number().nonnegative().nullable(), revenueAmount: z.number().nonnegative().nullable(), notes: z.string().trim().max(1000).nullable() });

export function ActivityDrawer({ orgId, fieldId, seasons, activity, selectedSeasonId, onClose }: { orgId: string; fieldId: string; seasons: SeasonSummary[]; activity?: Activity; selectedSeasonId?: string; onClose: () => void }) {
  const client = useQueryClient(); const { toast } = useToast();
  const { register, handleSubmit, formState: { errors } } = useForm<ActivityInput>({ resolver: zodResolver(schema), defaultValues: { seasonId: activity?.seasonId ?? selectedSeasonId ?? seasons[0]?.id ?? "", type: activity?.type ?? "planting", activityDate: activity?.activityDate ?? new Date().toISOString().slice(0, 10), quantity: activity?.quantity ?? null, quantityUnit: activity?.quantityUnit ?? null, costAmount: activity?.costAmount ?? null, revenueAmount: activity?.revenueAmount ?? null, notes: activity?.notes ?? null } });
  const mutation = useMutation({ mutationFn: (values: ActivityInput) => apiFetch<ActivityResponse>(activity ? `/api/orgs/${orgId}/activities/${activity.id}` : `/api/orgs/${orgId}/fields/${fieldId}/activities`, { method: activity ? "PATCH" : "POST", body: JSON.stringify(values) }), onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ["orgs", orgId, "fields", fieldId, "activities"] }), client.invalidateQueries({ queryKey: queryKeys.field(orgId, fieldId) }), client.invalidateQueries({ queryKey: queryKeys.dashboard(orgId) }), client.invalidateQueries({ queryKey: queryKeys.insights(orgId) })]); toast({ type: "success", title: activity ? "Activity updated" : "Activity logged" }); onClose(); }, onError: (error) => toast({ type: "danger", title: "Could not save activity", description: error instanceof Error ? error.message : undefined }) });
  return <Dialog footer={<><Button onClick={onClose} variant="secondary">Cancel</Button><Button loading={mutation.isPending} onClick={handleSubmit((values) => mutation.mutate(values))}>{activity ? "Save changes" : "Log activity"}</Button></>} onClose={onClose} open title={activity ? "Edit activity" : "Log activity"}><form className="space-y-4" onSubmit={handleSubmit((values) => mutation.mutate(values))}>
    <div className="grid gap-4 sm:grid-cols-2"><div><label className="form-label" htmlFor="activity-type">Type</label><select className="form-control" id="activity-type" {...register("type")}>{types.map((type) => <option key={type} value={type}>{type.charAt(0).toUpperCase() + type.slice(1)}</option>)}</select></div><div><label className="form-label" htmlFor="activity-date">Date</label><input className="form-control font-mono" id="activity-date" type="date" aria-invalid={Boolean(errors.activityDate)} {...register("activityDate")} /><FieldError id="activity-date-error" message={errors.activityDate?.message} /></div></div>
    <div><label className="form-label" htmlFor="activity-season">Season</label><select className="form-control" id="activity-season" aria-invalid={Boolean(errors.seasonId)} {...register("seasonId")}>{seasons.map((season) => <option key={season.id} value={season.id}>{season.name}</option>)}</select><FieldError id="activity-season-error" message={errors.seasonId?.message} /></div>
    <div className="grid gap-4 sm:grid-cols-2"><div><label className="form-label" htmlFor="activity-quantity">Quantity <span className="font-normal text-ink-faint">(optional)</span></label><input className="form-control font-mono" id="activity-quantity" min="0" step="0.01" type="number" {...register("quantity", { setValueAs: (value) => value === "" ? null : Number(value) })} /></div><div><label className="form-label" htmlFor="activity-unit">Unit <span className="font-normal text-ink-faint">(optional)</span></label><input className="form-control" id="activity-unit" placeholder="bu, gal, lb" {...register("quantityUnit", { setValueAs: (value) => value === "" ? null : value })} /></div></div>
    <div className="grid gap-4 sm:grid-cols-2"><div><label className="form-label" htmlFor="activity-cost">Cost <span className="font-normal text-ink-faint">(optional)</span></label><input className="form-control font-mono" id="activity-cost" min="0" step="0.01" type="number" {...register("costAmount", { setValueAs: (value) => value === "" ? null : Number(value) })} /></div><div><label className="form-label" htmlFor="activity-revenue">Revenue <span className="font-normal text-ink-faint">(optional)</span></label><input className="form-control font-mono" id="activity-revenue" min="0" step="0.01" type="number" {...register("revenueAmount", { setValueAs: (value) => value === "" ? null : Number(value) })} /></div></div>
    <div><label className="form-label" htmlFor="activity-notes">Notes <span className="font-normal text-ink-faint">(optional)</span></label><textarea className="form-control" id="activity-notes" {...register("notes", { setValueAs: (value) => value === "" ? null : value })} /></div>
  </form></Dialog>;
}
